"""ClaudeGenerator — โหมด AI จริง (เรียก Anthropic Messages API).

เป็น "จุดเดียว" ที่ส่งข้อมูลออกนอกเครื่อง และทำงานเฉพาะเมื่อผู้ใช้ตั้ง ANTHROPIC_API_KEY เอง
model id ปรับได้ผ่าน env SDD_MODEL (ค่าเริ่มต้น claude-sonnet-5)
"""
import os
import json
from .base import Generator, FileArtifact
from ..stages import OUTPUTS, STAGE_BY_ID

SYSTEM = (
    "You are a Spec-Driven Development engine (like GitHub Spec Kit). "
    "For the given stage you produce artifact files. "
    "Respond with ONLY a JSON object, no prose, no markdown fences, of the exact shape: "
    '{"files":[{"path":"<relative path>","content":"<full file content>"}],"note":"<one short line>"}. '
    "Use EXACTLY the file paths you are told to produce. Keep content realistic and internally consistent "
    "with the prior artifacts you are given."
)

STAGE_INSTRUCTIONS = {
    "constitution": "Write project engineering principles (API-first, test-first, simplicity, observability). Markdown.",
    "specify": "Write a feature specification: WHAT/WHY only, NO technology. Include user stories, acceptance "
               "scenarios, FR-001.. functional requirements, key entities. Mark unknowns with [NEEDS CLARIFICATION].",
    "clarify": "Update the specification by resolving every [NEEDS CLARIFICATION] using the human answers provided. "
               "Return the full updated spec.md.",
    "plan": "Produce the implementation plan (tech choices, Constitution Check gate), a data-model.md, an "
            "OpenAPI contract (openapi.yaml), and a quickstart.md. Contract must precede code.",
    "tasks": "Break the plan into dependency-ordered, TDD-ordered tasks T001.. Tests come before implementation. "
             "Mark parallelizable tasks with [P]. Markdown.",
    "implement": "Write the actual source code and tests that satisfy the spec, plan and contract. Produce the "
                 "exact files requested. Tests must be runnable with pytest.",
    "analyze": "Cross-check spec vs plan vs tasks vs code for gaps/inconsistencies. Return a short markdown report.",
}


def _extract_json(text: str) -> dict:
    text = text.strip()
    if text.startswith("```"):
        text = text.split("```", 2)[1]
        if text.startswith("json"):
            text = text[4:]
    start, end = text.find("{"), text.rfind("}")
    if start == -1 or end == -1:
        raise ValueError("Claude did not return JSON")
    return json.loads(text[start:end + 1])


class ClaudeGenerator(Generator):
    name = "claude"

    def __init__(self):
        from anthropic import Anthropic  # import แบบ lazy — ไม่บังคับติดตั้งถ้าไม่ใช้
        self.client = Anthropic()        # อ่าน ANTHROPIC_API_KEY จาก env
        self.model = os.environ.get("SDD_MODEL", "claude-sonnet-5")

    def generate(self, stage_id: str, context: dict):
        want_paths = OUTPUTS[stage_id]
        prior = context.get("prior") or {}
        prior_txt = "\n\n".join(f"### {p}\n{c[:4000]}" for p, c in prior.items()) or "(none yet)"

        prompt = (
            f"STAGE: {STAGE_BY_ID[stage_id]['cmd']}\n"
            f"TASK: {STAGE_INSTRUCTIONS[stage_id]}\n"
            f"FEATURE: {context.get('feature', 'unnamed feature')}\n"
            f"HUMAN INPUT: {json.dumps(context.get('user_input') or {}, ensure_ascii=False)}\n\n"
            f"PRIOR ARTIFACTS:\n{prior_txt}\n\n"
            f"PRODUCE EXACTLY THESE FILE PATHS: {json.dumps(want_paths)}"
        )

        msg = self.client.messages.create(
            model=self.model,
            max_tokens=8000,
            system=SYSTEM,
            messages=[{"role": "user", "content": prompt}],
        )
        text = "".join(b.text for b in msg.content if getattr(b, "type", None) == "text")
        data = _extract_json(text)
        files = [FileArtifact(f["path"], f["content"]) for f in data.get("files", [])]
        if not files:
            raise ValueError("Claude returned no files")
        return files, data.get("note", "generated by Claude")
